import FWCore.ParameterSet.Config as cms

process = cms.Process("PLOT")

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_1_1_X99.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_2_1_pjL.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_3_1_qZ5.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_4_2_JGv.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_5_2_qVq.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_6_2_mm8.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_7_2_oQt.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_8_2_fy5.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_9_2_aOA.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_10_2_jUR.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_11_2_eXF.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_12_2_NDZ.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_13_1_1z8.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_14_1_SN1.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_15_1_4Dw.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_16_2_Nh6.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_17_2_0rL.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_18_1_70C.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_19_1_RFn.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_20_1_BJN.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_21_1_5gE.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_22_2_yse.root',
##     'dcap://cmsdca.fnal.gov:24136/pnfs/cms/WAX/11/store/user/lpcgg/askew/ThreePhotonSkim/Photon_Run2010B-Nov4ReReco_v1_RECO/EG_HLTPhoton_23_2_duA.root'
    
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG001.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG002.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG003.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG004.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG005.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG006.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG007.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG008.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG009.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG010.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG011.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG012.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG013.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG014.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG015.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG016.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG017.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG018.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG019.root',
     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG020.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG021.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG022.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG023.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG024.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG025.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG026.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG027.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG028.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG029.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG030.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG031.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG032.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG033.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG034.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG035.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG036.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG037.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG038.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG039.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG040.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG041.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG042.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG043.root',
     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG044.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG045.root',
     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG046.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG047.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG048.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG049.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG050.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG051.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG052.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG053.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG054.root',
     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG055.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG056.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG057.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG058.root',
     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG059.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG060.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG061.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG062.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG063.root',
##     'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/EG/PhotonEventSelectorFromEG064.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton001.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton002.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton003.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton004.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton005.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton006.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton007.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton008.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton009.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton010.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton011.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton012.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton013.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton014.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton015.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton016.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton017.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton018.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton019.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton020.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton021.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton022.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton023.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton024.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton025.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton026.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton027.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton028.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton029.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton030.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton031.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton032.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton033.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton034.root',
    'file:/uscms_data/d2/csilkw2/CMSSW_3_8_7/src/SWGuideEJTermPhotonAnalysis/PhotonEventSelector/test/output/Photon/PhotonEventSelectorFromPhoton035.root'
 

    )
)
process.options = cms.untracked.PSet(
  fileMode = cms.untracked.string('NOMERGE')
)
process.analyzer = cms.EDAnalyzer('PhotonPlots',
                                  HistOutFile = cms.untracked.string('PhotonPlots_SkimSat2.root')
                                  )



process.p = cms.Path(process.analyzer)

process.load("FWCore.MessageLogger.MessageLogger_cfi")
process.MessageLogger.cerr.FwkReport.reportEvery = 1000
